# Generated by Django 5.1.1 on 2024-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
